### ISSUE TITLE
Printing IP or hostname with windows session fails

### ISSUE THREAD

**Issue by pevogam** [avocado-framework/aexpect#116]
There is some problem with windows sessions when using the session prefix like:
```
[stdlog] 2023-02-07 13:40:58,382 aexpect.client WARNI| Failed to print_line '()' '192.168.51.1Please wait...'
[stdlog] 2023-02-07 13:40:58,382 aexpect.client WARNI| Failed to print_line '()' '192.168.51.1Microsoft Windows [Version 10.0.14393]'
[stdlog] 2023-02-07 13:40:58,382 aexpect.client WARNI| Failed to print_line '()' '192.168.51.1(c) 2016 Microsoft Corporation. Alle Rechte vorbehalten.'
[stdlog] 2023-02-07 13:40:58,382 aexpect.client WARNI| Failed to print_line '()' '192.168.51.1'
```
I will investigate this shortly but after recent changes of avocado removed the logged line in the format I will have to run in a special older environment first.

**Comment by ldoktor** [comment]
Hello Plamen, this is happening when the `self.output_func` is not set and we flush the data on line `678` or `682`. I meant to look at that but got more important matters.

**Comment by ldoktor** [comment]
(alternatively it might happen when we have `self.output_func` set when we get to line 668 and then removed before we run line 635 or 633)

**Comment by ldoktor** [comment]
Note these were there all the time, they were just silently ignored. IIRC I wanted to leave it on warning for now to evaluate later. Would you have any preference? The `_print_line` function is kind-of performance intensive so I'd prefer not putting there yet another check for `self.output_func`, but perhaps we could only warn when `self.output_params` are used plus also add the `if self.output_func` to the lines 677 and 681.

**Comment by ldoktor** [comment]
https://github.com/avocado-framework/aexpect/pull/117 this tackles the extra places where we ought to check `self.output_func` presence, I have tested that and it made a huge difference in my workflow (lots of previously neglected warnings are gone). As I mentioned earlier, we could still get the warning in case the user changes `self.output_func`, but fixing that would require locking and I don't think the benefit would be so big (functionally it would be fine, only a warning might appear when `self.output_func` is removed).

**Comment by pevogam** [comment]
@ldoktor Since so far we did what we could here and this turned out to be a false alarm of something already known it is better to close it. Let's see if later redesigns might help us improve on this further when the right time comes.

**Comment by PaulYuuu** [comment]
Hello @pevogam, I also hit this problem, and after investigation, I think the following code should be updated.
https://github.com/avocado-framework/aexpect/blob/5182d378ddb44c904a29425dc766295d418bb2db/aexpect/remote.py#L417-L429
After the session is created, `output_func` and `output_params` are still empty for a very short time, but the session wants to log some messages. So sometimes, when `session.set_output_func(log_function)` is executed but `session.set_output_params((log_filename,))` is not yet, we still have this problem. A possible change is to modify the code like this:
```diff
diff --git a/aexpect/remote.py b/aexpect/remote.py
index d7e09ec..01d7207 100644
--- a/aexpect/remote.py
+++ b/aexpect/remote.py
@@ -414,7 +414,8 @@ def remote_login(client, host, port, username, password, prompt, linesep="\n",

     if verbose:
         LOG.debug("Login command: '%s'", cmd)
-    session = RemoteSession(cmd, linesep=linesep, output_prefix=host,
+    session = RemoteSession(cmd, linesep=linesep, output_func=log_function,
+                            output_params=(log_filename,), output_prefix=host,
                             prompt=prompt, status_test_command=status_test_command,
                             client=client, host=host, port=port,
                             username=username, password=password)
@@ -424,8 +425,6 @@ def remote_login(client, host, port, username, password, prompt, linesep="\n",
         session.close()
         raise
     if log_filename:
-        session.set_output_func(log_function)
-        session.set_output_params((log_filename,))
         session.set_log_file(os.path.basename(log_filename))
     return session
```

Then we can correctly set `output_func` and `output_params` before logging messages.

**Comment by pevogam** [comment]
Hi @PaulYuuu, sounds like an interesting suggestion. I just wonder if there was a clear motivation for us to bundle the log filename and function together with the `log_file` attribute and bind/couple these behaviors. Checking the history it seems they were always together also in Avocado VT and were merely migrated together under the `if log_filename` conditional by me as I did not touch the original logic unless completely necessary.

**Comment by PaulYuuu** [comment]
> Hi @PaulYuuu, sounds like an interesting suggestion. I just wonder if there was a clear motivation for us to bundle the log filename and function together with the `log_file` attribute and bind/couple these behaviors. Checking the history it seems they were always together also in Avocado VT and were merely migrated together under the `if log_filename` conditional by me as I did not touch the original logic unless completely necessary.

Actually, I saw `RemoteSession` can handle `output_func` and `output_params` natively, so we can move `set_output_func`/`set_output_params` to the initialization stage. Avocado VT only has a few calls of this function, but I am not sure about other projects, unless we need to change log_func during test, I would recommend the above code change.

However, the problem is not 100% percentage reproducible, so not sure the change can address this problem indeed, And I made a mistake in that in this change we need to ensure log_filename is not `None`.

**Comment by pevogam** [comment]
> > Hi @PaulYuuu, sounds like an interesting suggestion. I just wonder if there was a clear motivation for us to bundle the log filename and function together with the `log_file` attribute and bind/couple these behaviors. Checking the history it seems they were always together also in Avocado VT and were merely migrated together under the `if log_filename` conditional by me as I did not touch the original logic unless completely necessary.
> 
> Actually, I saw `RemoteSession` can handle `output_func` and `output_params` natively, so we can move `set_output_func`/`set_output_params` to the initialization stage. Avocado VT only has a few calls of this function, but I am not sure about other projects, unless we need to change log_func during test, I would recommend the above code change.

Indeed a good point about the `RemoteSession` that explains this, however I wonder if we could simply extend it later on to also incorporate the `session.set_log_file(os.path.basename(log_filename))` line so that we don't have to separate similar functionality and increase complexity of configuring log files in multiple locations. Perhaps you could propose a pull request with a complete change here? Even if it doesn't fix the various printed IP/hostname problems discussed in this issue it might be a refactoring improvement to consider.

> However, the problem is not 100% percentage reproducible, so not sure the change can address this problem indeed, And I made a mistake in that in this change we need to ensure log_filename is not `None`.

Nevertheless, if you think it can actually improve this configuration and make better use of the API (e.g. the RemoteSession class) feel free to open a pull request. I will close this issue again since the diff suggestion above seems more like an improvement of the overall aexpect interface.
