### ISSUE TITLE
Python 3: passing fd compatibility issue

### ISSUE THREAD

**Issue by luckyh** [avocado-framework/aexpect#30]
A command launched by `Spawn`/`Tail`/`Expect`/`ShellSession` will not work properly with using python 3 when it wants its parent process to pass fd to it, for instance, launching a qemu vm with tap devices.
```
MALLOC_PERTURB_=1  /bin/qemu-kvm \
    ...
    -netdev tap,id=id9JSepX,vhost=on,vhostfd=22,fd=15 \
    ...
[qemu output] qemu-system-x86_64: -netdev tap,id=id9JSepX,vhost=on,vhostfd=22,fd=15: TUNGETIFF ioctl() failed: Bad file descriptor
[qemu output] TUNSETOFFLOAD ioctl() failed: Bad file descriptor
```
That because the following things are changed in python 3:

1. the default value of argument `close_fds` of class `subprocess.Popen` has been changed to `True` in python 3.2, so that users can not use this feature to pass fd to the given command since `Spawn` would not set `close_fds` for `Popen`.
2. although we can set `close_fds=False` for `Popen` in `Spawn` (this is risky, see below explanation), users still need to call `fcntl` to unset `FD_CLOEXEC` for the fd they want to pass in python 3.

Well, there are some solutions:

1. set `close_fds=False` for `Popen` in `Spawn` and let users unset `FD_CLOEXEC`, but I think it is bad because that would result in fd leaks.
2. make a new argument `pass_fds` for `Spawn`/`Tail`/`Expect`/`ShellSession` like what `Popen` did in python 3.2, however, it is not easy to implement since we have to write a custom `Popen` for python 2.
3. say we do not support passing fd.

I will choose the second one if I have to.

@clebergnu @ldoktor @lmr any ideas?

**Comment by ldoktor** [comment]
I haven't looked at this deeply, but my first idea would be (2) along with documentation explaining that on py2 it'll always act as True. But I'll have to look at the details...

**Comment by luckyh** [comment]
@ldoktor ok, that makes sense.

I just made a solution (https://github.com/avocado-framework/aexpect/pull/32) for this, please help review it, thanks.

**Comment by luckyh** [comment]
resolved by https://github.com/avocado-framework/aexpect/pull/34
