### ISSUE TITLE
tag python3 compatible release

### ISSUE THREAD

**Issue by mmathesius** [avocado-framework/aexpect#36]
To assist with Fedora packaging, could someone please create a git tag for a new `aexpect` release that is considered compatible with python3? Python3 support was still incomplete in the latest tagged release (1.4.0) nearly 14 months ago. Thanks!

**Comment by ldoktor** [comment]
@lmr I think this is on you ... Perhaps it'd be nice to include https://github.com/avocado-framework/aexpect/pull/35 as well so new RPM packages can be built.

**Comment by lmr** [comment]
@mmathesius and @ldoktor I did tag 1.5.0 yesterday, with #35, I hope everything is fine now.

**Comment by mmathesius** [comment]
Thanks, @lmr. I'll get a Fedora `python-aexpect-1.5.0` package put together shortly for Python 2 and 3.

**Comment by mmathesius** [comment]
I have created https://src.fedoraproject.org/rpms/python-aexpect/pull-request/2 to sync the Fedora `python-aexpect` package with release 1.5.0 and include full support for python 3. That PR also includes a workaround to the `setup.py` glitch with EPEL7 I reported in https://github.com/avocado-framework/aexpect/issues/38
