### ISSUE TITLE
RFC: Use select.poll for waiting on file descriptors

### ISSUE THREAD

**Issue by fabianorosas** [avocado-framework/aexpect#44]
I'm running stress_boot.py [1] from the avocado-vt plugin and avocado is failing to boot the 60th (or so) guest:
```
L0651 DEBUG| [stderr] Traceback (most recent call last):
L0651 DEBUG| [stderr]   File "/usr/lib64/python2.7/threading.py", line 812, in __bootstrap_inner
L0651 DEBUG| [stderr]     self.run()
L0651 DEBUG| [stderr]   File "/usr/lib64/python2.7/threading.py", line 765, in run
L0651 DEBUG| [stderr]     self.__target(*self.__args, **self.__kwargs)
L0651 DEBUG| [stderr]   File "/usr/lib/python2.7/site-packages/aexpect/client.py", line 584, in _tail
L0651 DEBUG| [stderr]     r, w, x = select.select([fd], [], [], 0.05)
L0651 DEBUG| [stderr] ValueError: filedescriptor out of range in select()
```

`ls -l /proc/<pid>/fd | wc -l` shows ~1040 by the time this fails.

From `man select` I see that this is expected:
> select() can monitor only file descriptors numbers that are less than FD_SETSIZE; poll(2) does not have this limitation.  See BUGS.

`select.select` is used in aexpect in 3 places, here is one of them:
```
                try:
                    # See if there's any data to read from the pipe
                    read_available_fds = select.select([tail_pipe], [], [],
                                                       0.05)[0]
                except (select.error, TypeError):
                    break
                if tail_pipe in read_available_fds:
                    # Some data is available; read it
                    new_data = os.read(tail_pipe, 1024)
```

So, I altered the code to use `select.poll` in aexpect (and virttest) and stress_boot can now boot 200 guests.

I'm still to rebase it on top of the latest version but I wanted to hear what you guys think first. I'm not sure about the compatibilty with other platforms, I see that pexpect has a switch to choose between select and poll: https://github.com/pexpect/pexpect/commit/6db8d9b8e91a49c75bf67a95f245733d357770a8 

---
More info:
```
$ ulimit -n
65536

$ uname -r
4.11.0-44.el7a.ppc64le

$ rpm -qa | grep "avocado\|aexpect"
python2-aexpect-1.5.1-1.el7.noarch
python2-avocado-62.0-0.el7.noarch
avocado-plugins-vt-62.0-0.el7.noarch
python-avocado-common-62.0-0.el7.noarch

$ avocado run io-github-autotest-qemu.stress_boot --vt-type qemu --vt-arch ppc64le --vt-extra-params nettype=user max_vms=200
```
1- https://github.com/autotest/tp-qemu/blob/master/generic/tests/stress_boot.py

**Comment by ldoktor** [comment]
Yep, it makes sense to me, only I'd like to avoid yet another argument so I'd suggest to always use `poll` when available and fallback to `select` when it's missing. @fabianorosas do you intend develop this or do you want us to work on it?

**Comment by fabianorosas** [comment]
@ldoktor yes, I'm working on it. I'll send a pull request soon.
