### ISSUE TITLE
Aexpect needs to be released

### ISSUE THREAD

**Issue by sathnaga** [avocado-framework/aexpect#62]
As aexpect module dependency is resolved through pip install, 
it needs to be tagged and released to get new features by
other repositories.

**Comment by pevogam** [comment]
> As aexpect module dependency is resolved through pip install,
> it needs to be tagged and released to get new features by
> other repositories.

FYI, the last person we pinged for this was @lmr but he didn't do it and I am not sure who else could do it. Will be waiting for any input on any alternatives.

**Comment by sathnaga** [comment]
@ldoktor @clebergnu needs help here.

**Comment by clebergnu** [comment]
> @ldoktor @clebergnu needs help here.

Please help review https://github.com/avocado-framework/aexpect/pull/63, and then I'll cut a release.

**Comment by clebergnu** [comment]
It's out:

https://pypi.org/project/aexpect/1.6.0/

Thanks for your patience guys!

**Comment by pevogam** [comment]
Thanks @clebergnu for speeding things up and @sathnaga for focusing the attention of more maintainers to this!
