### ISSUE TITLE
Enable all pylint checks

### ISSUE THREAD

**Issue by clebergnu** [avocado-framework/aexpect#64]
There's a number of pylint checks being disabled, either globally or in-place.  Let's attempt to have no exceptions and all pylint checks enabled.

**Comment by pevogam** [comment]
Note to self: @pevogam must recheck and get rid of pylint W0201 in the exception deserialization of the remote door utility.

**Comment by pevogam** [comment]
More recently added disable statements to be fixed after the release (assuming python 3 only): W0707, R1725

**Comment by pevogam** [comment]
@clebergnu @ldoktor I have addressed all pyling issues noted here in #68

**Comment by ldoktor** [comment]
@pevogam unless I'm wrong all the issues were addressed, right?

**Comment by pevogam** [comment]
I think so yes.
