### ISSUE TITLE
Migrating remote's 2019-20 newly developed features to aexpect

### ISSUE THREAD

**Issue by pevogam** [avocado-framework/aexpect#69]
Because the PR migrating the `remote.py` functionality took more than a year, a lot of developments happened and continued modifying the their copy of the module. I am creating this issue to track progress on catching up with these new features here and potential problems that may arise with the migration on the Avocado VT side.

This issue is also the place to track hotfixes related to the remote functionality migration if and when such are necessary.

**Comment by pevogam** [comment]
I am writing here a list of collected previously conflicting PRs that we should recheck in order to make sure no development progress was lost during the remote utility migration:

- https://github.com/avocado-framework/avocado-vt/pull/2727
- https://github.com/avocado-framework/avocado-vt/pull/2720
- https://github.com/avocado-framework/avocado-vt/pull/2703
- https://github.com/avocado-framework/avocado-vt/pull/2327

Some more PR could follow here.

**Comment by pevogam** [comment]
@dzhengfy, @Yingshun, @xiaodwan do you have any other suggestions from other PR-s about what the original aexpect remote module must provide?

From what I can see all of your changes above have already been reflected in the original remote module [here](https://github.com/avocado-framework/aexpect/blob/master/aexpect/remote.py) and we can soon proceed to dropping the temporary placeholder functionality from the avocado-vt/remote.

**Comment by dzhengfy** [comment]
@pevogam , current avocado-vt/virttest/remote.py already invokes functions in aexpect/remote.py, like handle_prompts(), so they have no overlaps now. So I am confused about your question. Do we need to move all of left functions in avocado-vt/virttest/remote.py  to aexpect/remote.py?
 Current class/functions in avocado-vt/virrtest/remote.py , like RemoteFile, RemoteRunner , VMManager, are widely used in tp-libvirt.

**Comment by pevogam** [comment]
> @pevogam , current avocado-vt/virttest/remote.py already invokes functions in aexpect/remote.py, like handle_prompts(), so they have no overlaps now. So I am confused about your question. Do we need to move all of left functions in avocado-vt/virttest/remote.py to aexpect/remote.py?

We have functions like `ssh_login_to_migrate` and `wait_for_ssh_login_to_migrate` in Avocado VT which were meant to be fully dropped there with Avocado VT making direct use of the `aexpect.remote` versions. To the best of my knowledge these could be dropped no on the Avocado VT side and no more migration of related Avocado VT functionality is needed here (thus we can close this issue), do you agree?

> Current class/functions in avocado-vt/virrtest/remote.py , like RemoteFile, RemoteRunner , VMManager, are widely used in tp-libvirt.

Classes like RemoteFile, RemoteRunner, and VMManager were not meant to be generalized to aexpect/session scope and I am not even sure what it the current use of the first two that is not already available in aexpect other than the class wrapper.

**Comment by dzhengfy** [comment]
@pevogam , for functions ssh_login_to_migrate() and wait_for_ssh_login_to_migrate() in Avocado VT virttest/remote.py,  I agree to remove them because there is not any reference to them in tp-libvirt and tp-qemu till now. So it is safe to directly remove them.

But for other classes like RemoteFile, RemoteRunner, and VMManager , there are references in tp-libvirt now, so we would like to keep them in virttest/remote.py.

I will take National holidays leave for next whole week, so I will follow this issue when I am back. Thanks.

**Comment by pevogam** [comment]
> @pevogam , for functions ssh_login_to_migrate() and wait_for_ssh_login_to_migrate() in Avocado VT virttest/remote.py, I agree to remove them because there is not any reference to them in tp-libvirt and tp-qemu till now. So it is safe to directly remove them.

Alright, I pushed https://github.com/avocado-framework/avocado-vt/pull/3534 on the Avocado VT side which is ready for review for when you are back.

> But for other classes like RemoteFile, RemoteRunner, and VMManager , there are references in tp-libvirt now, so we would like to keep them in virttest/remote.py.

That's fine by me, I do not understand their purpose and I believe aexpect could fully replace them but as long as the aexpect side functionality is feature complete this is ok.

> I will take National holidays leave for next whole week, so I will follow this issue when I am back. Thanks.

Alright, enjoy your vacation!

**Comment by pevogam** [comment]
Since the pull request was reviewed and merged, it is time to close this.
