### ISSUE TITLE
No tag for 1.6.1

### ISSUE THREAD

**Issue by pevogam** [avocado-framework/aexpect#71]
As discussed in https://github.com/avocado-framework/avocado-vt/pull/2811# and as I wrote in particular [here](https://github.com/avocado-framework/avocado-vt/pull/2811#issuecomment-721027373) and [here](https://github.com/avocado-framework/avocado-vt/pull/2811#issuecomment-721039205), the tag and thus downloadable tarball for v1.6.1 is missing so I will be glad if any of the aexpect maintainers tags the release commit.

**Comment by pevogam** [comment]
In some way (see my second comment) this issue is related to https://github.com/avocado-framework/aexpect/pull/66.

**Comment by lmr** [comment]
Sorry guys, I totally forgot to git push --tags:

`git push --tags
Enumerating objects: 1, done.
Counting objects: 100% (1/1), done.
Writing objects: 100% (1/1), 173 bytes | 173.00 KiB/s, done.
Total 1 (delta 0), reused 0 (delta 0), pack-reused 0
To github.com:avocado-framework/aexpect.git
 * [new tag]         1.6.1 -> 1.6.1
`

**Comment by lmr** [comment]
It's done now, sorry about the hassle.
