### ISSUE TITLE
remote_login has no parameter to accept -X for ssh session

### ISSUE THREAD

**Issue by kamilvarga** [avocado-framework/aexpect#85]
The SSH session cannot be created with -X parameter as there is no place for this parameter in remote_login method. I would suggest to update the "verbose" parameter to allow user to pass something from allowed values, like -v or -X. I am going to prepare patch for this.

**Comment by kamilvarga** [comment]
PR created to fix this issue: https://github.com/avocado-framework/aexpect/pull/86

**Comment by pevogam** [comment]
As the PR was merged can we close this issue?

**Comment by ldoktor** [comment]
Yep, thank you
