### ISSUE TITLE
The `cmd_output_safe` function doesn't do what it promises by its choice of name

### ISSUE THREAD

**Issue by pevogam** [avocado-framework/aexpect#93]
Hi all,

While investigating a simple case where we have to read a file through an aexpect session with one-line content like
```
abc
```
without a newline delimiter in the end and trying to resolve the error `Timeout expired while waiting for shell command to complete: 'cat /some/file'    (output: 'abc[root@vm1 ~]# ')` using the _safe option `cmd_output_safe` it seems like it is not implemented correctly. In particular, if you look at the current implementation
```python
        LOG.debug("Sending command (safe): %s", cmd)
        self.read_nonblocking(0, timeout)
        self.sendline(cmd)
        out = ""
        success = False
        start_time = time.time()
        while (time.time() - start_time) < timeout:
            try:
                out += self.read_up_to_prompt(0.5)
                success = True
                break
            except ExpectTimeoutError as error:
                self.sendline()
```
it seems like in the above example the line `out += self.read_up_to_prompt(0.5)` will fail and `out` won't be populated with the output (here `abc[root@vm1 ~]# `), then we will do `self.sendline()` and succeed on the next try, however returning an output with the new line but without `abc`. Is this the actually anticipated behavior or am I missing something?

**Comment by ldoktor** [comment]
Hello Plamen, you are right, according to the definition it should extend the out in case of any exception. I'm a bit afraid it might break someone's workflow but the current solutions is quite fragile for longer outputs so fixing it should be better. Do you want to go ahead and send a PR or do you want me to work on that?

**Comment by pevogam** [comment]
Thanks for replying @ldoktor. I can work on that, I just needed to know that is indeed an issue that can be acknowledged by more people and now I got a maintainer confirming it which is enough for me to go ahead.

**Comment by ldoktor** [comment]
Sure, as far as I know this feature is not that frequently used. I am only using it on places where the full output is not that important but your fixes should actually improve the output reproducibility so let's hope it won't critically break someone's workflow.

**Comment by pevogam** [comment]
Closing this via https://github.com/avocado-framework/aexpect/pull/88.
